ASP.NET/Controllers/IngredientController.cs
using ASP.NET.Models;
using Microsoft.AspNetCore.Mvc;
using YourNamespace.Data;

namespace ASP.NET.Controllers;

public class IngredientController : Controller
{
    private Repository<Ingredient> ingredients;

    public IngredientController(YoussefDbContext context)
    {
        ingredients = new Repository<Ingredient>(context);
    }
    // GET
    public async Task<IActionResult> Index()
    {
        return View(await ingredients.GetAllAsync());
    }
    
    public async Task<IActionResult> Details(int id)
    {
        return View(await ingredients.GetByIdAsync(id, new QueryOptions<Ingredient>() {Includes = "ProductIngredients.Product"}));
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("IngredientId , Name")] Ingredient ingredient)
    {
        if (ModelState.IsValid)
        {
            await ingredients.AddAsync(ingredient);
            return RedirectToAction("Index");
        }

        return View(ingredient);
    }
    
    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        return View(await ingredients.GetByIdAsync(id, new QueryOptions<Ingredient>{ Includes = "ProductIngredients.Product"}));
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id, Ingredient ingredient)
    {
        await ingredients.DeleteAsync(id);
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        return View(await ingredients.GetByIdAsync(id, new QueryOptions<Ingredient>{ Includes = "ProductIngredients.Product"}));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Ingredient ingredient)
    {
        if (ModelState.IsValid)
        {
            await ingredients.UpdateAsync(ingredient);
            return RedirectToAction("Index");
        }
        return  View(ingredient);
    }
}

ASP.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ASP.NET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ASP.NET.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Ingredient" asp-action="Index">Ingredient</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Menu Items</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - ASP.NET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>